AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create the resources necessary for hosting a simple personal static website

Parameters:
  DomainName:
    Description: Name of domain to bind hosted zone to (do not include "www.")
    Type: String
    Default: colliepa.ws
  DomainCertificate:
    Description: ARN of ACM certificate fort the domain to host
    Type: String
  HostedZoneId:
    Description: Hosted zone ID for S3 buckets in this region
    Type: String
    Default: Z2FDTNDATAQYW2
  VpcCidrBlock:
    Description: CIDR Block to allocate VPC
    Type: String
    Default: 10.0.0.0/16

Resources:
  # may not need?
  Vpc:
    Type: AWS::EC2::VPC
    Description: Test VPC (probably unnecessary right now)
    Properties: 
      CidrBlock: !Ref VpcCidrBlock

  # may not need?
  Dns: 
    Type: AWS::Route53::HostedZone
    Properties: 
      HostedZoneConfig: 
        Comment: Hosted zone for static site
      Name: !Ref DomainName

  RecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      Comment: DNS name for static S3
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt CloudfrontDistribution.DomainName
          HostedZoneId: !Ref HostedZoneId
      - Name: !Sub www.${DomainName}
        Type: CNAME
        TTL: 900
        ResourceRecords:
        - !GetAtt RedirectCloudFrontDistribution.DomainName

  RootS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
  WwwRootS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub www.${DomainName}
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref DomainName
          Protocol: https

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: S3OpenAccessPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref RootS3Bucket
                - /*
      Bucket: !Ref RootS3Bucket

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Comment: Cloudfront distribution for HTTPS support
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          - OPTIONS
          Compress: true
          TargetOriginId: RootS3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !GetAtt RootS3Bucket.DomainName
          Id: RootS3Origin
          S3OriginConfig:
            OriginAccessIdentity: '' # TODO: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref DomainCertificate
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only

  # Because of www. we also need a cloudfront to redirect to the www bucket which will redirect to the APEX
  RedirectCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub www.${DomainName}
        Comment: www redirect
        DefaultCacheBehavior:
          TargetOriginId: WwwRootS3Origin
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: true
            Cookies:
             Forward: none
          ViewerProtocolPolicy: allow-all
        Enabled: true
        HttpVersion: http2
        Origins:
        - DomainName: !GetAtt WwwRootS3Bucket.DomainName
          Id: WwwRootS3Origin
          S3OriginConfig:
            OriginAccessIdentity: ''
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref DomainCertificate
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only